# TCL File Generated by Component Editor 21.1
# Tue May 13 16:48:56 EDT 2025
# DO NOT MODIFY


# 
# audio_play "Audio Play" v1.0
#  2025.05.13.16:48:56
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module audio_play
# 
set_module_property DESCRIPTION ""
set_module_property NAME audio_play
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "Audio Play"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL audio_play
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file audio_play.sv SYSTEM_VERILOG PATH audio_play.sv TOP_LEVEL_FILE
add_fileset_file audio_rom.v VERILOG PATH audio_rom.v
add_fileset_file audio_sample.mif MIF PATH audio_sample.mif


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point audio_ctrl
# 
add_interface audio_ctrl conduit end
set_interface_property audio_ctrl associatedClock clock
set_interface_property audio_ctrl associatedReset reset
set_interface_property audio_ctrl ENABLED true
set_interface_property audio_ctrl EXPORT_OF ""
set_interface_property audio_ctrl PORT_NAME_MAP ""
set_interface_property audio_ctrl CMSIS_SVD_VARIABLES ""
set_interface_property audio_ctrl SVD_ADDRESS_GROUP ""

add_interface_port audio_ctrl audio_ctrl audio_ctrl Input 3


# 
# connection point avalon_left_channel_source
# 
add_interface avalon_left_channel_source avalon_streaming start
set_interface_property avalon_left_channel_source associatedClock clock
set_interface_property avalon_left_channel_source associatedReset reset
set_interface_property avalon_left_channel_source dataBitsPerSymbol 8
set_interface_property avalon_left_channel_source errorDescriptor ""
set_interface_property avalon_left_channel_source firstSymbolInHighOrderBits true
set_interface_property avalon_left_channel_source maxChannel 0
set_interface_property avalon_left_channel_source readyLatency 0
set_interface_property avalon_left_channel_source ENABLED true
set_interface_property avalon_left_channel_source EXPORT_OF ""
set_interface_property avalon_left_channel_source PORT_NAME_MAP ""
set_interface_property avalon_left_channel_source CMSIS_SVD_VARIABLES ""
set_interface_property avalon_left_channel_source SVD_ADDRESS_GROUP ""

add_interface_port avalon_left_channel_source sample_data_l data Output 16
add_interface_port avalon_left_channel_source sample_valid_l valid Output 1
add_interface_port avalon_left_channel_source left_chan_ready ready Input 1


# 
# connection point avalon_right_channel_source
# 
add_interface avalon_right_channel_source avalon_streaming start
set_interface_property avalon_right_channel_source associatedClock clock
set_interface_property avalon_right_channel_source associatedReset reset
set_interface_property avalon_right_channel_source dataBitsPerSymbol 8
set_interface_property avalon_right_channel_source errorDescriptor ""
set_interface_property avalon_right_channel_source firstSymbolInHighOrderBits true
set_interface_property avalon_right_channel_source maxChannel 0
set_interface_property avalon_right_channel_source readyLatency 0
set_interface_property avalon_right_channel_source ENABLED true
set_interface_property avalon_right_channel_source EXPORT_OF ""
set_interface_property avalon_right_channel_source PORT_NAME_MAP ""
set_interface_property avalon_right_channel_source CMSIS_SVD_VARIABLES ""
set_interface_property avalon_right_channel_source SVD_ADDRESS_GROUP ""

add_interface_port avalon_right_channel_source sample_valid_r valid Output 1
add_interface_port avalon_right_channel_source right_chan_ready ready Input 1
add_interface_port avalon_right_channel_source sample_data_r data Output 16

