# TCL File Generated by Component Editor 21.1
# Tue May 13 02:17:35 EDT 2025
# DO NOT MODIFY


# 
# vga_top "VGA Top" v1.0
#  2025.05.13.02:17:35
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module vga_top
# 
set_module_property DESCRIPTION ""
set_module_property NAME vga_top
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "VGA Top"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL vga_top
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file vga_top.sv SYSTEM_VERILOG PATH vga_top.sv TOP_LEVEL_FILE
add_fileset_file linebuffer.sv SYSTEM_VERILOG PATH linebuffer.sv
add_fileset_file linebuffer_ram.v VERILOG PATH linebuffer_ram.v
add_fileset_file tilemap.v VERILOG PATH tilemap.v
add_fileset_file tiles.mif MIF PATH tiles.mif
add_fileset_file tilemap.mif MIF PATH tilemap.mif
add_fileset_file tile_engine.sv SYSTEM_VERILOG PATH tile_engine.sv
add_fileset_file tile_pattern.v VERILOG PATH tile_pattern.v
add_fileset_file sprite_drawer.sv SYSTEM_VERILOG PATH sprite_drawer.sv
add_fileset_file sprite_engine.sv SYSTEM_VERILOG PATH sprite_engine.sv
add_fileset_file sprite_frontend.sv SYSTEM_VERILOG PATH sprite_frontend.sv
add_fileset_file sprite_pattern_rom.v VERILOG PATH sprite_pattern_rom.v
add_fileset_file tilemap_test.mif MIF PATH tilemap_test.mif
add_fileset_file tiles_test.mif MIF PATH tiles_test.mif
add_fileset_file sprite_attr_ram.v VERILOG PATH sprite_attr_ram.v
add_fileset_file sprites.mif MIF PATH sprites.mif
add_fileset_file sprites_test.mif MIF PATH sprites_test.mif


# 
# parameters
# 


# 
# module assignments
# 
set_module_assignment embeddedsw.dts.group "vga"
set_module_assignment embeddedsw.dts.name "vga_top"
set_module_assignment embeddedsw.dts.vendor "csee4840"


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset reset
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 writedata writedata Input 32
add_interface_port avalon_slave_0 write write Input 1
add_interface_port avalon_slave_0 chipselect chipselect Input 1
add_interface_port avalon_slave_0 address address Input 6
add_interface_port avalon_slave_0 readdata readdata Output 32
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point vga
# 
add_interface vga conduit end
set_interface_property vga associatedClock clock
set_interface_property vga associatedReset ""
set_interface_property vga ENABLED true
set_interface_property vga EXPORT_OF ""
set_interface_property vga PORT_NAME_MAP ""
set_interface_property vga CMSIS_SVD_VARIABLES ""
set_interface_property vga SVD_ADDRESS_GROUP ""

add_interface_port vga VGA_B b Output 8
add_interface_port vga VGA_BLANK_n blank_n Output 1
add_interface_port vga VGA_CLK clk Output 1
add_interface_port vga VGA_G g Output 8
add_interface_port vga VGA_HS hs Output 1
add_interface_port vga VGA_R r Output 8
add_interface_port vga VGA_SYNC_n sync_n Output 1
add_interface_port vga VGA_VS vs Output 1


# 
# connection point audio_ctrl
# 
add_interface audio_ctrl conduit end
set_interface_property audio_ctrl associatedClock clock
set_interface_property audio_ctrl associatedReset reset
set_interface_property audio_ctrl ENABLED true
set_interface_property audio_ctrl EXPORT_OF ""
set_interface_property audio_ctrl PORT_NAME_MAP ""
set_interface_property audio_ctrl CMSIS_SVD_VARIABLES ""
set_interface_property audio_ctrl SVD_ADDRESS_GROUP ""

add_interface_port audio_ctrl audio_ctrl audio_ctrl Output 3

