// flood_fill_tb — exercises hw/ip/mcts_accel/flood_fill.sv against vectors
// generated by sw/golden/gen_vectors.py.
//
// Input file format (sim/vectors/ff_vectors.txt):
//   <seed_bit:21hex> <propagate:21hex> <liberty:21hex>
//   <expected_group:21hex> <expected_size:2hex> <expected_has_lib:1hex> [# name]
//
// Output file (flood_fill_dut.txt) echoes inputs + DUT-produced outputs,
// formatted identically so sw/golden/compare.py can diff field-by-field.

`timescale 1ns/1ps

import mcts_accel_pkg::*;

module flood_fill_tb;

    logic clk;
    logic reset_n;
    logic start;
    logic [80:0] seed_bit;
    logic [80:0] propagate_mask;
    logic [80:0] liberty_mask;
    logic [80:0] group_mask;
    logic [6:0]  group_size;
    logic        has_liberty;
    logic        done;

    flood_fill dut (
        .clk(clk), .reset_n(reset_n), .start(start),
        .seed_bit(seed_bit),
        .propagate_mask(propagate_mask),
        .liberty_mask(liberty_mask),
        .group_mask(group_mask),
        .group_size(group_size),
        .has_liberty(has_liberty),
        .done(done)
    );

    // Clock
    initial clk = 0;
    always #5 clk = ~clk;  // 100 MHz

    integer fi, fo, code;
    logic [80:0] exp_group;
    logic [6:0]  exp_size;
    logic        exp_lib;

    initial begin
        reset_n = 0;
        start   = 0;
        #20;
        reset_n = 1;
        #20;

        fi = $fopen("vectors/ff_vectors.txt", "r");
        fo = $fopen("flood_fill_dut.txt", "w");
        if (fi == 0 || fo == 0) begin
            $display("ERROR: failed to open vectors/ff_vectors.txt or DUT output");
            $finish;
        end

        while (!$feof(fi)) begin
            // Skip comment lines (start with '#') by reading first hex; if
            // that fails, advance one line.
            code = $fscanf(fi, " %h %h %h %h %h %h\n",
                           seed_bit, propagate_mask, liberty_mask,
                           exp_group, exp_size, exp_lib);
            if (code != 6) begin
                // skip rest of line
                begin : skip
                    integer ch;
                    ch = $fgetc(fi);
                    while (ch != -1 && ch != "\n") ch = $fgetc(fi);
                end
                continue;
            end

            // Pulse start, wait for done
            @(posedge clk);
            start <= 1;
            @(posedge clk);
            start <= 0;
            while (!done) @(posedge clk);

            $fwrite(fo, "%021h %021h %021h %021h %02h %1h\n",
                    seed_bit, propagate_mask, liberty_mask,
                    group_mask, group_size, has_liberty);

            // Give DUT a cycle to return to IDLE
            @(posedge clk);
        end

        $fclose(fi);
        $fclose(fo);
        $display("flood_fill_tb done");
        $finish;
    end

endmodule
