# go_peripheral_hw.tcl — Qsys component descriptor
#
# Modeled on FlappyBird's vga_ball_hw.tcl (CSEE 4840 Spring 2025), with the
# component renamed and pointed at our go_peripheral.sv. The Avalon slave
# shape (write-only, 3-bit byte-addressed, 8-bit data) matches lab3 exactly,
# which is the proven import path. We will widen this when Phase 2 adds real
# registers.
#
# IMPORTANT: this file is normally generated by the Platform Designer
# Component Editor. We hand-author it here to keep it in version control;
# Quartus 16.1+ will accept it as-is. If you edit via the Component Editor
# and re-save, the comment header at the top will be replaced.

package require -exact qsys 16.1

# ─── Module identity ─────────────────────────────────────────────────────────
set_module_assignment embeddedsw.dts.vendor "csee4840"
set_module_assignment embeddedsw.dts.name   "go_peripheral"
set_module_assignment embeddedsw.dts.group  "vga"
set_module_property NAME                   go_peripheral
set_module_property VERSION                1.0
set_module_property INTERNAL               false
set_module_property OPAQUE_ADDRESS_MAP     true
set_module_property AUTHOR                 "Comfere/Cooper"
set_module_property DISPLAY_NAME           "Go Peripheral"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE               true
set_module_property REPORT_TO_TALKBACK     false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY       false
set_module_property DESCRIPTION            "9x9 Go game peripheral: VGA + audio (audio added Phase 6)"

# ─── File set ────────────────────────────────────────────────────────────────
# Phase 2: now multi-file (go_peripheral.sv + board_mem.sv). When you re-import
# this IP in Platform Designer after Phase 2 changes, both files must be
# present in hw/. Quartus picks them up via this fileset.
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL go_peripheral
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file go_peripheral.sv SYSTEM_VERILOG PATH go_peripheral.sv TOP_LEVEL_FILE
add_fileset_file board_mem.sv     SYSTEM_VERILOG PATH board_mem.sv
add_fileset_file strip_fb.sv      SYSTEM_VERILOG PATH strip_fb.sv

# ─── Clock sink ──────────────────────────────────────────────────────────────
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
add_interface_port clock clk clk Input 1

# ─── Reset sink ──────────────────────────────────────────────────────────────
add_interface reset reset end
set_interface_property reset associatedClock     clock
set_interface_property reset synchronousEdges    DEASSERT
set_interface_property reset ENABLED             true
add_interface_port reset reset reset Input 1

# ─── Avalon slave ────────────────────────────────────────────────────────────
# Shape: write-only, 3-bit byte address, 8-bit data — same as lab3 vga_ball.
# bitsPerSymbol=8, addressUnits=WORDS with word size = 1 byte.
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits                  WORDS
set_interface_property avalon_slave_0 associatedClock               clock
set_interface_property avalon_slave_0 associatedReset               reset
set_interface_property avalon_slave_0 bitsPerSymbol                 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly    false
set_interface_property avalon_slave_0 burstcountUnits               WORDS
set_interface_property avalon_slave_0 explicitAddressSpan           0
set_interface_property avalon_slave_0 holdTime                      0
set_interface_property avalon_slave_0 linewrapBursts                false
set_interface_property avalon_slave_0 maximumPendingReadTransactions  0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency                   0
set_interface_property avalon_slave_0 readWaitTime                  1
set_interface_property avalon_slave_0 setupTime                     0
set_interface_property avalon_slave_0 timingUnits                   Cycles
set_interface_property avalon_slave_0 writeWaitTime                 0
set_interface_property avalon_slave_0 ENABLED                       true
add_interface_port avalon_slave_0 writedata   writedata   Input 8
add_interface_port avalon_slave_0 write       write       Input 1
add_interface_port avalon_slave_0 chipselect  chipselect  Input 1
add_interface_port avalon_slave_0 address     address     Input 3
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash             0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice      0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice   0

# ─── Avalon slave 1 (Phase 5: strip framebuffer write window) ───────────────
# 32-bit data, 14-bit word address (covers all 9,600 valid words; addresses
# >= 9600 are silently ignored by strip_fb.sv).
add_interface avalon_slave_1 avalon end
set_interface_property avalon_slave_1 addressUnits                  WORDS
set_interface_property avalon_slave_1 associatedClock               clock
set_interface_property avalon_slave_1 associatedReset               reset
set_interface_property avalon_slave_1 bitsPerSymbol                 8
set_interface_property avalon_slave_1 burstOnBurstBoundariesOnly    false
set_interface_property avalon_slave_1 burstcountUnits               WORDS
set_interface_property avalon_slave_1 explicitAddressSpan           0
set_interface_property avalon_slave_1 holdTime                      0
set_interface_property avalon_slave_1 linewrapBursts                false
set_interface_property avalon_slave_1 maximumPendingReadTransactions  0
set_interface_property avalon_slave_1 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_1 readLatency                   0
set_interface_property avalon_slave_1 readWaitTime                  1
set_interface_property avalon_slave_1 setupTime                     0
set_interface_property avalon_slave_1 timingUnits                   Cycles
set_interface_property avalon_slave_1 writeWaitTime                 0
set_interface_property avalon_slave_1 ENABLED                       true
add_interface_port avalon_slave_1 strip_writedata  writedata   Input 32
add_interface_port avalon_slave_1 strip_write      write       Input 1
add_interface_port avalon_slave_1 strip_chipselect chipselect  Input 1
add_interface_port avalon_slave_1 strip_address    address     Input 14
set_interface_assignment avalon_slave_1 embeddedsw.configuration.isFlash             0
set_interface_assignment avalon_slave_1 embeddedsw.configuration.isMemoryDevice      1
set_interface_assignment avalon_slave_1 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_1 embeddedsw.configuration.isPrintableDevice   0

# ─── VGA conduit (exported through Qsys to top-level pins) ──────────────────
add_interface vga conduit end
set_interface_property vga associatedClock clock
set_interface_property vga associatedReset ""
set_interface_property vga ENABLED         true
add_interface_port vga VGA_B       b       Output 8
add_interface_port vga VGA_BLANK_n blank_n Output 1
add_interface_port vga VGA_CLK     clk     Output 1
add_interface_port vga VGA_G       g       Output 8
add_interface_port vga VGA_HS      hs      Output 1
add_interface_port vga VGA_R       r       Output 8
add_interface_port vga VGA_SYNC_n  sync_n  Output 1
add_interface_port vga VGA_VS      vs      Output 1
